[package]
name = "wiki-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.37.1"
tokio = { version = "1.42.0", features = ["full"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres" ] }
